import mongoose from 'mongoose';
import env from '../config/env';
import logger from '../config/logger';
import User from '../models/User';
import Category from '../models/Category';
import Product from '../models/Product';
import ProductImage from '../models/ProductImage';
import bcrypt from 'bcryptjs';

// ============================================================
// RentHub Demo Seed
// ============================================================
// Creates 12 unique rental products with local demo images so the
// marketplace looks like a real production demo, and removes
// internal test/smoke products ("Smoke Test Camera", "Test Camera
// for Rent", "test-product") from the demo database.
//
// Real user-created products (titles that do not match the test
// patterns) are preserved. Existing users & categories are upserted
// so nothing else is destroyed.
// ============================================================

const CATEGORIES: Array<{
  name: string;
  slug: string;
  icon: string;
  image: string;
  description: string;
  subcategories: string[];
}> = [
  { name: 'Laptops', slug: 'laptops', icon: 'Laptop', image: '/images/demo/laptop.svg', description: 'Premium laptops and notebooks for rent by the day', subcategories: ['MacBooks', 'Windows Ultrabooks', 'Business Laptops'] },
  { name: 'Cameras', slug: 'cameras', icon: 'Camera', image: '/images/demo/camera.svg', description: 'DSLRs, mirrorless cameras and photography gear', subcategories: ['DSLR', 'Mirrorless', 'Action Cameras'] },
  { name: 'Speakers', slug: 'speakers', icon: 'Speaker', image: '/images/demo/speaker.svg', description: 'Party speakers and portable Bluetooth audio', subcategories: ['Party Speakers', 'Portable Speakers'] },
  { name: 'Drones', slug: 'drones', icon: 'Plane', image: '/images/demo/drone.svg', description: 'Camera drones for aerial photography and videography', subcategories: ['Camera Drones', 'Mini Drones', 'FPV'] },
  { name: 'Projectors', slug: 'projectors', icon: 'MonitorPlay', image: '/images/demo/projector.svg', description: 'Home theatre and business projectors for rent', subcategories: ['Home Theatre', 'Business', 'Mini Projectors'] },
  { name: 'Gaming', slug: 'gaming', icon: 'Gamepad2', image: '/images/demo/gaming-console.svg', description: 'Gaming consoles, controllers and accessories', subcategories: ['Consoles', 'Controllers', 'VR'] },
  { name: 'Sports', slug: 'sports', icon: 'Bike', image: '/images/demo/bicycle.svg', description: 'Cycles, fitness and outdoor sports equipment', subcategories: ['Cycling', 'Fitness', 'Outdoor Sports'] },
  { name: 'Camping', slug: 'camping', icon: 'Tent', image: '/images/demo/camping.svg', description: 'Tents and camping gear for your next adventure', subcategories: ['Tents', 'Camping Gear', 'Hiking'] },
  { name: 'Smartphones', slug: 'smartphones', icon: 'Smartphone', image: '/images/demo/smartphone.svg', description: 'Latest smartphones available for short-term rental', subcategories: ['Flagships', 'Android', 'iPhone'] },
  { name: 'Tablets', slug: 'tablets', icon: 'Tablet', image: '/images/demo/tablet.svg', description: 'iPads and Android tablets for work and play', subcategories: ['iPad', 'Android Tablets'] },
  { name: 'Audio', slug: 'audio', icon: 'Headphones', image: '/images/demo/headphones.svg', description: 'Headphones, earbuds and personal audio devices', subcategories: ['Headphones', 'Earbuds', 'Noise Cancelling'] },
  { name: 'Wearables', slug: 'wearables', icon: 'Watch', image: '/images/demo/watch.svg', description: 'Smart watches and wearable tech for rent', subcategories: ['Smart Watches', 'Fitness Bands'] },
];

// Demo owners (upserted by email — existing users keep their ids).
const OWNERS = [
  {
    seedName: 'alex-owner',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    password: 'OwnerPass123',
    role: 'owner',
    phone: '+91 98765 43210',
    city: 'Pune',
    state: 'Maharashtra',
    verified: true,
  },
  {
    seedName: 'priya-owner',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    password: 'OwnerPass123',
    role: 'owner',
    phone: '+91 91234 56780',
    city: 'Mumbai',
    state: 'Maharashtra',
    verified: true,
  },
  {
    seedName: 'rahul-owner',
    name: 'Rahul Verma',
    email: 'rahul@example.com',
    password: 'OwnerPass123',
    role: 'owner',
    phone: '+91 99887 76655',
    city: 'Bengaluru',
    state: 'Karnataka',
    verified: true,
  },
];

const PRODUCTS: Array<{
  slug: string;
  title: string;
  description: string;
  categorySlug: string;
  ownerEmail: string;
  image: string;
  condition: 'new' | 'like_new' | 'good' | 'fair' | 'used';
  city: string;
  state: string;
  rentalPrice: number;
  deposit: number;
  rating: number;
  reviewCount: number;
  isFeatured: boolean;
  isTrending: boolean;
  features: string[];
  tags: string[];
  saleEnabled?: boolean;
  salePrice?: number;
  purchaseCondition?: string;
}> = [
  {
    slug: 'macbook-air-m2',
    title: 'MacBook Air M2',
    description: 'Ultra-thin MacBook Air M2 with 8-core CPU, 8GB unified memory and 256GB SSD. Perfect for travel, presentations and coding. Comes with charger and padded sleeve.',
    categorySlug: 'laptops',
    ownerEmail: 'alex@example.com',
    image: '/images/products/macbook-air-m2.jpg',
    condition: 'like_new',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 800,
    deposit: 5000,
    rating: 4.8,
    reviewCount: 24,
    isFeatured: true,
    isTrending: false,
    features: ['M2 8-core CPU', '8GB unified memory', '256GB SSD', 'Retina display', 'Charger included'],
    tags: ['macbook', 'laptop', 'apple', 'ultrabook', 'work'],
    saleEnabled: true,
    salePrice: 75000,
    purchaseCondition: 'Like New — includes original box, charger and padded sleeve',
  },
  {
    slug: 'canon-eos-1500d-camera',
    title: 'Canon EOS 1500D Camera',
    description: 'Canon EOS 1500D DSLR with 18-55mm kit lens, EF-S 24.1 megapixel sensor and full HD video. Ideal for product shoots, events and travel photography.',
    categorySlug: 'cameras',
    ownerEmail: 'priya@example.com',
    image: '/images/products/canon-eos-1500d.jpg',
    condition: 'good',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 700,
    deposit: 4000,
    rating: 4.7,
    reviewCount: 32,
    isFeatured: true,
    isTrending: false,
    features: ['24.1MP APS-C sensor', '18-55mm kit lens', 'Full HD video', 'SD card included', 'Camera bag'],
    tags: ['canon', 'dslr', 'camera', 'photography', 'lens'],
    saleEnabled: true,
    salePrice: 32000,
    purchaseCondition: 'Good — includes 18-55mm kit lens, SD card and camera bag',
  },
  {
    slug: 'jbl-partybox-speaker',
    title: 'JBL PartyBox Speaker',
    description: 'JBL PartyBox 310 portable party speaker with 240W output, deep bass, light show and up to 18 hours of playtime. Perfect for parties, events and gatherings.',
    categorySlug: 'speakers',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/jbl-partybox.jpg',
    condition: 'good',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 500,
    deposit: 3000,
    rating: 4.6,
    reviewCount: 41,
    isFeatured: false,
    isTrending: true,
    features: ['240W output', 'Built-in light show', '18-hour battery', 'Bluetooth/AUX', 'Wheels & handle'],
    tags: ['jbl', 'speaker', 'party', 'bluetooth', 'audio'],
  },
  {
    slug: 'dji-mini-drone',
    title: 'DJI Mini Drone',
    description: 'DJI Mini 3 Pro drone with 4K HDR video, 48MP photos, 3-axis gimbal and 34-minute flight time. Includes 2 batteries, remote controller and carrying case.',
    categorySlug: 'drones',
    ownerEmail: 'alex@example.com',
    image: '/images/products/dji-mini-drone.jpg',
    condition: 'like_new',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 1200,
    deposit: 8000,
    rating: 4.9,
    reviewCount: 18,
    isFeatured: true,
    isTrending: false,
    features: ['4K HDR video', '48MP photos', '3-axis gimbal', '34-min flight', '2 batteries'],
    tags: ['dji', 'drone', 'aerial', '4k', 'photography'],
    saleEnabled: true,
    salePrice: 45000,
    purchaseCondition: 'Like New — includes 2 batteries, remote controller and carrying case',
  },
  {
    slug: 'epson-projector',
    title: 'Epson Projector',
    description: 'Epson Full HD projector with 3000 lumens, HDMI/DVI connectivity and 120-inch projection. Great for movie nights, office presentations and events.',
    categorySlug: 'projectors',
    ownerEmail: 'priya@example.com',
    image: '/images/products/epson-projector.jpg',
    condition: 'good',
    city: 'Hyderabad',
    state: 'Telangana',
    rentalPrice: 600,
    deposit: 5000,
    rating: 4.5,
    reviewCount: 27,
    isFeatured: true,
    isTrending: false,
    features: ['Full HD 1080p', '3000 lumens', 'HDMI & VGA', '120" projection', 'Remote included'],
    tags: ['epson', 'projector', 'home theatre', 'presentation'],
    saleEnabled: true,
    salePrice: 38000,
    purchaseCondition: 'Good — includes remote, HDMI cable and carry case',
  },
  {
    slug: 'playstation-5',
    title: 'PlayStation 5',
    description: 'Sony PlayStation 5 with DualSense controller, 1TB SSD and 2 games included. Lightning-fast loading with ray tracing for an immersive gaming experience.',
    categorySlug: 'gaming',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/playstation-5.jpg',
    condition: 'like_new',
    city: 'Chennai',
    state: 'Tamil Nadu',
    rentalPrice: 900,
    deposit: 9000,
    rating: 4.9,
    reviewCount: 56,
    isFeatured: true,
    isTrending: false,
    features: ['1TB SSD', 'DualSense controller', '4K 120fps', '2 games included', 'HDMI cable'],
    tags: ['playstation', 'ps5', 'gaming', 'console', 'sony'],
    saleEnabled: true,
    salePrice: 45000,
    purchaseCondition: 'Like New — includes DualSense controller, 2 games and HDMI cable',
  },
  {
    slug: 'mountain-bicycle',
    title: 'Mountain Bicycle',
    description: '21-speed mountain bicycle with dual disc brakes, front suspension and 26-inch alloy wheels. Ideal for city rides, trails and weekend adventures.',
    categorySlug: 'sports',
    ownerEmail: 'alex@example.com',
    image: '/images/products/mountain-bicycle.jpg',
    condition: 'good',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 400,
    deposit: 2500,
    rating: 4.4,
    reviewCount: 22,
    isFeatured: false,
    isTrending: true,
    features: ['21-speed gears', 'Dual disc brakes', 'Front suspension', '26" alloy wheels', 'Helmet included'],
    tags: ['bicycle', 'cycle', 'mountain', 'sports', 'fitness'],
  },
  {
    slug: 'camping-tent',
    title: 'Camping Tent',
    description: 'Spacious 4-person camping tent with waterproof rainfly, UV protection and easy 10-minute setup. Great for camping trips, treks and beach outings.',
    categorySlug: 'camping',
    ownerEmail: 'priya@example.com',
    image: '/images/products/camping-tent.jpg',
    condition: 'new',
    city: 'Goa',
    state: 'Goa',
    rentalPrice: 450,
    deposit: 3000,
    rating: 4.3,
    reviewCount: 15,
    isFeatured: false,
    isTrending: true,
    features: ['4-person capacity', 'Waterproof rainfly', 'UV protection', '10-min setup', 'Carry bag'],
    tags: ['tent', 'camping', 'outdoor', 'adventure'],
  },
  {
    slug: 'samsung-galaxy-s24',
    title: 'Samsung Galaxy S24',
    description: 'Samsung Galaxy S24 with 6.2-inch AMOLED display, 50MP triple camera and all-day battery. Unlocked with 128GB storage and fast charging.',
    categorySlug: 'smartphones',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/samsung-galaxy-s24.jpg',
    condition: 'like_new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 600,
    deposit: 6500,
    rating: 4.7,
    reviewCount: 38,
    isFeatured: false,
    isTrending: true,
    features: ['6.2" AMOLED', '50MP triple camera', '128GB storage', 'All-day battery', 'Fast charging'],
    tags: ['samsung', 'galaxy', 'smartphone', 'android', 'phone'],
  },
  {
    slug: 'ipad-air',
    title: 'iPad Air',
    description: 'iPad Air 5th gen with 10.9-inch Liquid Retina display, M1 chip and Apple Pencil support. Perfect for design, notes, media and productivity on the go.',
    categorySlug: 'tablets',
    ownerEmail: 'alex@example.com',
    image: '/images/products/ipad-air.jpg',
    condition: 'like_new',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 650,
    deposit: 6000,
    rating: 4.8,
    reviewCount: 29,
    isFeatured: true,
    isTrending: false,
    features: ['10.9" Liquid Retina', 'M1 chip', 'Apple Pencil support', '64GB storage', 'Wi-Fi + 5G'],
    tags: ['ipad', 'tablet', 'apple', 'creative', 'productivity'],
    saleEnabled: true,
    salePrice: 55000,
    purchaseCondition: 'Like New — includes original box, charger and Apple Pencil',
  },
  {
    slug: 'sony-wh-1000xm5-headphones',
    title: 'Sony WH-1000XM5 Headphones',
    description: 'Sony WH-1000XM5 wireless noise-cancelling headphones with 30-hour battery, multipoint connection and studio-quality sound. Perfect for travel and focus.',
    categorySlug: 'audio',
    ownerEmail: 'priya@example.com',
    image: '/images/products/sony-wh1000xm5.jpg',
    condition: 'like_new',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 350,
    deposit: 2000,
    rating: 4.8,
    reviewCount: 63,
    isFeatured: false,
    isTrending: true,
    features: ['Industry-leading ANC', '30-hour battery', 'Multipoint connection', 'Hi-Res audio', 'Travel case'],
    tags: ['sony', 'headphones', 'noise cancelling', 'audio', 'wireless'],
  },
  {
    slug: 'smart-watch',
    title: 'Smart Watch',
    description: 'Fitness smart watch with AMOLED display, heart-rate and SpO2 monitoring, GPS and 7-day battery life. Ideal for workouts, tracking and daily wear.',
    categorySlug: 'wearables',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/smart-watch.jpg',
    condition: 'new',
    city: 'Jaipur',
    state: 'Rajasthan',
    rentalPrice: 250,
    deposit: 1500,
    rating: 4.2,
    reviewCount: 19,
    isFeatured: false,
    isTrending: true,
    features: ['AMOLED display', 'Heart-rate + SpO2', 'GPS tracking', '7-day battery', 'Water resistant'],
    tags: ['smartwatch', 'watch', 'fitness', 'wearable', 'health'],
  },
  // ============================================================
  // Additional Demo Products (30+)
  // ============================================================
  // ---- Laptops ----
  {
    slug: 'dell-inspiron-laptop',
    title: 'Dell Inspiron Laptop',
    description: 'Dell Inspiron 15 with Intel Core i5, 16GB RAM and 512GB SSD. Perfect for work, study and everyday computing with a full HD display.',
    categorySlug: 'laptops',
    ownerEmail: 'alex@example.com',
    image: '/images/products/dell-inspiron.jpg',
    condition: 'good',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 500,
    deposit: 4000,
    rating: 4.4,
    reviewCount: 28,
    isFeatured: false,
    isTrending: false,
    features: ['Intel Core i5', '16GB RAM', '512GB SSD', '15.6" Full HD', 'Windows 11'],
    tags: ['dell', 'laptop', 'windows', 'work', 'productivity'],
    saleEnabled: true,
    salePrice: 45000,
    purchaseCondition: 'Good — includes charger and laptop sleeve',
  },
  {
    slug: 'hp-pavilion-laptop',
    title: 'HP Pavilion Laptop',
    description: 'HP Pavilion 14 with AMD Ryzen 5, 8GB RAM and 256GB SSD. Lightweight and powerful for students and professionals on the go.',
    categorySlug: 'laptops',
    ownerEmail: 'priya@example.com',
    image: '/images/products/hp-pavilion.jpg',
    condition: 'like_new',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 450,
    deposit: 3500,
    rating: 4.5,
    reviewCount: 21,
    isFeatured: false,
    isTrending: false,
    features: ['AMD Ryzen 5', '8GB RAM', '256GB SSD', '14" FHD display', 'Backlit keyboard'],
    tags: ['hp', 'laptop', 'windows', 'student', 'portable'],
  },
  {
    slug: 'lenovo-thinkpad-laptop',
    title: 'Lenovo ThinkPad Laptop',
    description: 'Lenovo ThinkPad X1 Carbon with Intel Core i7, 16GB RAM and 512GB SSD. Business-grade durability with exceptional performance.',
    categorySlug: 'laptops',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/lenovo-thinkpad.jpg',
    condition: 'like_new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 700,
    deposit: 5000,
    rating: 4.7,
    reviewCount: 33,
    isFeatured: true,
    isTrending: false,
    features: ['Intel Core i7', '16GB RAM', '512GB SSD', '14" WUXGA', 'Military-grade durability'],
    tags: ['lenovo', 'thinkpad', 'laptop', 'business', 'premium'],
    saleEnabled: true,
    salePrice: 65000,
    purchaseCondition: 'Like New — includes charger, dock and sleeve',
  },
  {
    slug: 'asus-gaming-laptop',
    title: 'ASUS Gaming Laptop',
    description: 'ASUS ROG Strix G15 with RTX 3060, AMD Ryzen 7 and 144Hz display. Serious gaming performance with RGB keyboard and cooling.',
    categorySlug: 'laptops',
    ownerEmail: 'alex@example.com',
    image: '/images/products/asus-gaming-laptop.jpg',
    condition: 'good',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 1000,
    deposit: 8000,
    rating: 4.6,
    reviewCount: 45,
    isFeatured: true,
    isTrending: true,
    features: ['RTX 3060', 'AMD Ryzen 7', '144Hz display', '16GB RAM', 'RGB keyboard'],
    tags: ['asus', 'gaming', 'laptop', 'rtx', 'rog'],
    saleEnabled: true,
    salePrice: 85000,
    purchaseCondition: 'Good — includes charger and gaming mouse',
  },
  // ---- Cameras ----
  {
    slug: 'nikon-dslr-camera',
    title: 'Nikon DSLR Camera',
    description: 'Nikon D5600 DSLR with 24.2MP sensor, 18-55mm kit lens and 4K video. Great for photography enthusiasts and content creators.',
    categorySlug: 'cameras',
    ownerEmail: 'priya@example.com',
    image: '/images/products/nikon-dslr.jpg',
    condition: 'good',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 650,
    deposit: 4500,
    rating: 4.5,
    reviewCount: 26,
    isFeatured: false,
    isTrending: false,
    features: ['24.2MP sensor', '18-55mm kit lens', '4K video', 'Vari-angle touchscreen', 'Wi-Fi + Bluetooth'],
    tags: ['nikon', 'dslr', 'camera', 'photography', 'lens'],
  },
  {
    slug: 'sony-alpha-camera',
    title: 'Sony Alpha Camera',
    description: 'Sony Alpha A6400 mirrorless camera with 24.2MP APS-C sensor, 4K video and real-time eye AF. Perfect for vlogging and photography.',
    categorySlug: 'cameras',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/sony-alpha.jpg',
    condition: 'like_new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 800,
    deposit: 6000,
    rating: 4.8,
    reviewCount: 37,
    isFeatured: true,
    isTrending: false,
    features: ['24.2MP APS-C', '4K video', 'Real-time eye AF', '180° flip screen', 'Compact body'],
    tags: ['sony', 'alpha', 'mirrorless', 'camera', 'vlogging'],
    saleEnabled: true,
    salePrice: 55000,
    purchaseCondition: 'Like New — includes 16-50mm lens, battery and strap',
  },
  {
    slug: 'gopro-action-camera',
    title: 'GoPro Action Camera',
    description: 'GoPro Hero 11 with 5.3K video, HyperSmooth stabilization and waterproof to 10m. Perfect for adventure, travel and sports.',
    categorySlug: 'cameras',
    ownerEmail: 'alex@example.com',
    image: '/images/products/gopro-hero11.jpg',
    condition: 'new',
    city: 'Goa',
    state: 'Goa',
    rentalPrice: 400,
    deposit: 3000,
    rating: 4.7,
    reviewCount: 52,
    isFeatured: false,
    isTrending: true,
    features: ['5.3K video', 'HyperSmooth 5.0', 'Waterproof 10m', 'Front + rear screens', 'TimeWarp 3.0'],
    tags: ['gopro', 'action camera', 'adventure', 'sports', 'travel'],
  },
  {
    slug: 'canon-mirrorless-camera',
    title: 'Canon Mirrorless Camera',
    description: 'Canon EOS R50 mirrorless camera with 24.2MP sensor, 4K video and dual-pixel autofocus. Compact and powerful for creators.',
    categorySlug: 'cameras',
    ownerEmail: 'priya@example.com',
    image: '/images/products/canon-mirrorless.jpg',
    condition: 'like_new',
    city: 'Hyderabad',
    state: 'Telangana',
    rentalPrice: 750,
    deposit: 5500,
    rating: 4.6,
    reviewCount: 29,
    isFeatured: false,
    isTrending: false,
    features: ['24.2MP sensor', '4K 30fps video', 'Dual-pixel AF', 'Compact design', 'RF-S 18-45mm lens'],
    tags: ['canon', 'mirrorless', 'camera', 'eos', 'creator'],
    saleEnabled: true,
    salePrice: 48000,
    purchaseCondition: 'Like New — includes RF-S 18-45mm lens and battery',
  },
  // ---- Smartphones ----
  {
    slug: 'iphone-15-pro',
    title: 'iPhone 15 Pro',
    description: 'Apple iPhone 15 Pro with A17 Pro chip, titanium design and pro camera system. 128GB storage with Dynamic Island.',
    categorySlug: 'smartphones',
    ownerEmail: 'alex@example.com',
    image: '/images/products/iphone-15-pro.jpg',
    condition: 'like_new',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 800,
    deposit: 7000,
    rating: 4.9,
    reviewCount: 68,
    isFeatured: true,
    isTrending: true,
    features: ['A17 Pro chip', 'Titanium design', 'Pro camera system', '128GB storage', 'Dynamic Island'],
    tags: ['iphone', 'apple', 'smartphone', 'ios', 'premium'],
    saleEnabled: true,
    salePrice: 95000,
    purchaseCondition: 'Like New — includes original box, cable and case',
  },
  {
    slug: 'samsung-galaxy-s23',
    title: 'Samsung Galaxy S23',
    description: 'Samsung Galaxy S23 with Snapdragon 8 Gen 2, 50MP camera and 120Hz AMOLED display. 128GB storage with fast charging.',
    categorySlug: 'smartphones',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/samsung-galaxy-s23.jpg',
    condition: 'good',
    city: 'Chennai',
    state: 'Tamil Nadu',
    rentalPrice: 550,
    deposit: 5000,
    rating: 4.5,
    reviewCount: 31,
    isFeatured: false,
    isTrending: false,
    features: ['Snapdragon 8 Gen 2', '50MP camera', '120Hz AMOLED', '128GB storage', 'Fast charging'],
    tags: ['samsung', 'galaxy', 'smartphone', 'android', 'flagship'],
  },
  {
    slug: 'oneplus-12-smartphone',
    title: 'OnePlus 12 Smartphone',
    description: 'OnePlus 12 with Snapdragon 8 Gen 3, Hasselblad camera and 120Hz ProXDR display. 256GB storage with 100W fast charging.',
    categorySlug: 'smartphones',
    ownerEmail: 'priya@example.com',
    image: '/images/products/oneplus-12.jpg',
    condition: 'new',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 600,
    deposit: 5500,
    rating: 4.6,
    reviewCount: 24,
    isFeatured: false,
    isTrending: true,
    features: ['Snapdragon 8 Gen 3', 'Hasselblad camera', '120Hz ProXDR', '256GB storage', '100W charging'],
    tags: ['oneplus', 'smartphone', 'android', 'flagship', 'hasselblad'],
  },
  {
    slug: 'google-pixel-8',
    title: 'Google Pixel 8',
    description: 'Google Pixel 8 with Tensor G3, 50MP camera and AI-powered features. 128GB storage with 7 years of updates.',
    categorySlug: 'smartphones',
    ownerEmail: 'alex@example.com',
    image: '/images/products/google-pixel-8.jpg',
    condition: 'like_new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 500,
    deposit: 4500,
    rating: 4.4,
    reviewCount: 18,
    isFeatured: false,
    isTrending: false,
    features: ['Tensor G3', '50MP camera', 'AI features', '128GB storage', '7-year updates'],
    tags: ['google', 'pixel', 'smartphone', 'android', 'ai'],
  },
  // ---- Gaming ----
  {
    slug: 'xbox-series-x',
    title: 'Xbox Series X',
    description: 'Xbox Series X with 1TB SSD, 4K gaming and Game Pass ready. Includes wireless controller and HDMI cable.',
    categorySlug: 'gaming',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/xbox-series-x.jpg',
    condition: 'like_new',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 850,
    deposit: 8000,
    rating: 4.7,
    reviewCount: 42,
    isFeatured: true,
    isTrending: false,
    features: ['1TB SSD', '4K 120fps', 'Wireless controller', 'Game Pass ready', 'Quick resume'],
    tags: ['xbox', 'series x', 'gaming', 'console', 'microsoft'],
    saleEnabled: true,
    salePrice: 42000,
    purchaseCondition: 'Like New — includes controller, HDMI and power cable',
  },
  {
    slug: 'nintendo-switch',
    title: 'Nintendo Switch',
    description: 'Nintendo Switch with 6.2" screen, Joy-Con controllers and dock. Play at home or on the go with 2 games included.',
    categorySlug: 'gaming',
    ownerEmail: 'priya@example.com',
    image: '/images/products/nintendo-switch.jpg',
    condition: 'good',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 500,
    deposit: 5000,
    rating: 4.6,
    reviewCount: 38,
    isFeatured: false,
    isTrending: true,
    features: ['6.2" screen', 'Joy-Con controllers', 'Dock included', '2 games included', 'Portable + TV mode'],
    tags: ['nintendo', 'switch', 'gaming', 'console', 'portable'],
  },
  {
    slug: 'gaming-pc',
    title: 'Gaming PC',
    description: 'High-performance gaming PC with RTX 4070, Intel Core i7 and 32GB RAM. 1TB NVMe SSD for lightning-fast load times.',
    categorySlug: 'gaming',
    ownerEmail: 'alex@example.com',
    image: '/images/products/gaming-pc.jpg',
    condition: 'like_new',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 1200,
    deposit: 10000,
    rating: 4.8,
    reviewCount: 27,
    isFeatured: true,
    isTrending: false,
    features: ['RTX 4070', 'Intel Core i7', '32GB RAM', '1TB NVMe SSD', 'RGB cooling'],
    tags: ['gaming', 'pc', 'rtx', 'desktop', 'esports'],
    saleEnabled: true,
    salePrice: 120000,
    purchaseCondition: 'Like New — includes keyboard, mouse and monitor',
  },
  {
    slug: 'vr-headset',
    title: 'VR Headset',
    description: 'Meta Quest 3 VR headset with 4K+ resolution, hand tracking and 128GB storage. Immersive gaming and experiences.',
    categorySlug: 'gaming',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/vr-headset.jpg',
    condition: 'new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 700,
    deposit: 6000,
    rating: 4.5,
    reviewCount: 22,
    isFeatured: false,
    isTrending: true,
    features: ['4K+ resolution', 'Hand tracking', '128GB storage', 'Wireless', 'Mixed reality'],
    tags: ['vr', 'headset', 'meta', 'quest', 'gaming'],
  },
  // ---- Audio ----
  {
    slug: 'bluetooth-speaker',
    title: 'Bluetooth Speaker',
    description: 'Portable Bluetooth speaker with 360° sound, 20-hour battery and IPX7 waterproof. Perfect for parties and outdoor events.',
    categorySlug: 'audio',
    ownerEmail: 'priya@example.com',
    image: '/images/products/bluetooth-speaker.jpg',
    condition: 'good',
    city: 'Goa',
    state: 'Goa',
    rentalPrice: 200,
    deposit: 1500,
    rating: 4.3,
    reviewCount: 35,
    isFeatured: false,
    isTrending: false,
    features: ['360° sound', '20-hour battery', 'IPX7 waterproof', 'Bluetooth 5.0', 'Built-in mic'],
    tags: ['bluetooth', 'speaker', 'audio', 'portable', 'party'],
  },
  {
    slug: 'bose-headphones',
    title: 'Bose Headphones',
    description: 'Bose QuietComfort 45 wireless headphones with world-class noise cancellation and 24-hour battery life.',
    categorySlug: 'audio',
    ownerEmail: 'alex@example.com',
    image: '/images/products/bose-headphones.jpg',
    condition: 'like_new',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 300,
    deposit: 2500,
    rating: 4.7,
    reviewCount: 44,
    isFeatured: false,
    isTrending: false,
    features: ['Noise cancellation', '24-hour battery', 'Bluetooth 5.1', 'Comfortable fit', 'Carry case'],
    tags: ['bose', 'headphones', 'noise cancelling', 'audio', 'wireless'],
    saleEnabled: true,
    salePrice: 22000,
    purchaseCondition: 'Like New — includes carry case and USB-C cable',
  },
  {
    slug: 'wireless-microphone',
    title: 'Wireless Microphone',
    description: 'Professional wireless microphone system with dual mics, 50m range and 8-hour battery. Perfect for content creation and events.',
    categorySlug: 'audio',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/wireless-microphone.jpg',
    condition: 'new',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 250,
    deposit: 2000,
    rating: 4.4,
    reviewCount: 16,
    isFeatured: false,
    isTrending: true,
    features: ['Dual mics', '50m range', '8-hour battery', 'USB-C charging', 'Noise reduction'],
    tags: ['microphone', 'wireless', 'audio', 'content', 'recording'],
  },
  {
    slug: 'sound-system',
    title: 'Sound System',
    description: 'Complete sound system with 2 speakers, subwoofer and mixer. 500W output for events, parties and gatherings.',
    categorySlug: 'audio',
    ownerEmail: 'alex@example.com',
    image: '/images/products/sound-system.jpg',
    condition: 'good',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 800,
    deposit: 6000,
    rating: 4.5,
    reviewCount: 29,
    isFeatured: true,
    isTrending: false,
    features: ['500W output', '2 speakers + subwoofer', 'Mixer included', 'Bluetooth + AUX', 'Speaker stands'],
    tags: ['sound', 'system', 'speakers', 'audio', 'event'],
    saleEnabled: true,
    salePrice: 35000,
    purchaseCondition: 'Good — includes speakers, subwoofer, mixer and cables',
  },
  // ---- Sports ----
  {
    slug: 'cricket-kit',
    title: 'Cricket Kit',
    description: 'Complete cricket kit with bat, pads, helmet, gloves and ball. Perfect for matches, practice and tournaments.',
    categorySlug: 'sports',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/cricket-kit.jpg',
    condition: 'good',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 350,
    deposit: 3000,
    rating: 4.4,
    reviewCount: 25,
    isFeatured: false,
    isTrending: false,
    features: ['Cricket bat', 'Pads + gloves', 'Helmet', 'Cricket ball', 'Kit bag'],
    tags: ['cricket', 'kit', 'sports', 'bat', 'match'],
  },
  {
    slug: 'badminton-set',
    title: 'Badminton Set',
    description: 'Professional badminton set with 2 rackets, 6 shuttlecocks and carry bag. Great for casual play and tournaments.',
    categorySlug: 'sports',
    ownerEmail: 'priya@example.com',
    image: '/images/products/badminton-set.jpg',
    condition: 'new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 150,
    deposit: 1000,
    rating: 4.2,
    reviewCount: 20,
    isFeatured: false,
    isTrending: false,
    features: ['2 rackets', '6 shuttlecocks', 'Carry bag', 'Lightweight', 'Grip tape'],
    tags: ['badminton', 'racket', 'sports', 'shuttle', 'game'],
  },
  {
    slug: 'football-kit',
    title: 'Football Kit',
    description: 'Complete football kit with ball, cones, bibs and pump. Perfect for training sessions and friendly matches.',
    categorySlug: 'sports',
    ownerEmail: 'alex@example.com',
    image: '/images/products/football-kit.jpg',
    condition: 'good',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 200,
    deposit: 1500,
    rating: 4.3,
    reviewCount: 17,
    isFeatured: false,
    isTrending: false,
    features: ['Football', 'Training cones', 'Bibs', 'Ball pump', 'Carry bag'],
    tags: ['football', 'kit', 'sports', 'soccer', 'training'],
  },
  {
    slug: 'fitness-equipment',
    title: 'Fitness Equipment',
    description: 'Home fitness equipment set with dumbbells, resistance bands, yoga mat and skipping rope. Complete workout at home.',
    categorySlug: 'sports',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/fitness-equipment.jpg',
    condition: 'like_new',
    city: 'Chennai',
    state: 'Tamil Nadu',
    rentalPrice: 300,
    deposit: 2500,
    rating: 4.5,
    reviewCount: 31,
    isFeatured: false,
    isTrending: true,
    features: ['Dumbbells set', 'Resistance bands', 'Yoga mat', 'Skipping rope', 'Workout guide'],
    tags: ['fitness', 'gym', 'equipment', 'workout', 'home'],
  },
  // ---- Camping ----
  {
    slug: 'sleeping-bag',
    title: 'Sleeping Bag',
    description: 'Warm sleeping bag rated to 0°C with compression sack. Compact and comfortable for camping and trekking.',
    categorySlug: 'camping',
    ownerEmail: 'priya@example.com',
    image: '/images/products/sleeping-bag.jpg',
    condition: 'new',
    city: 'Goa',
    state: 'Goa',
    rentalPrice: 120,
    deposit: 800,
    rating: 4.3,
    reviewCount: 23,
    isFeatured: false,
    isTrending: false,
    features: ['0°C rating', 'Compression sack', 'Lightweight', 'Water-resistant', 'Comfortable lining'],
    tags: ['sleeping', 'bag', 'camping', 'outdoor', 'trekking'],
  },
  {
    slug: 'camping-chair',
    title: 'Camping Chair',
    description: 'Foldable camping chair with cup holder and carry bag. Comfortable seating for outdoor adventures.',
    categorySlug: 'camping',
    ownerEmail: 'alex@example.com',
    image: '/images/products/camping-chair.jpg',
    condition: 'good',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 80,
    deposit: 500,
    rating: 4.1,
    reviewCount: 14,
    isFeatured: false,
    isTrending: false,
    features: ['Foldable design', 'Cup holder', 'Carry bag', 'Steel frame', 'Comfortable fabric'],
    tags: ['camping', 'chair', 'outdoor', 'folding', 'portable'],
  },
  {
    slug: 'portable-stove',
    title: 'Portable Stove',
    description: 'Portable camping stove with gas canister and cooking set. Cook delicious meals anywhere outdoors.',
    categorySlug: 'camping',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/portable-stove.jpg',
    condition: 'like_new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 150,
    deposit: 1000,
    rating: 4.4,
    reviewCount: 19,
    isFeatured: false,
    isTrending: false,
    features: ['Portable design', 'Gas canister', 'Cooking set', 'Wind-resistant', 'Carry case'],
    tags: ['stove', 'camping', 'cooking', 'outdoor', 'portable'],
  },
  {
    slug: 'trekking-bag',
    title: 'Trekking Bag',
    description: '60L trekking backpack with rain cover, hydration sleeve and multiple compartments. Perfect for multi-day treks.',
    categorySlug: 'camping',
    ownerEmail: 'alex@example.com',
    image: '/images/products/trekking-bag.jpg',
    condition: 'good',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 200,
    deposit: 1500,
    rating: 4.5,
    reviewCount: 27,
    isFeatured: false,
    isTrending: true,
    features: ['60L capacity', 'Rain cover', 'Hydration sleeve', 'Multiple compartments', 'Adjustable straps'],
    tags: ['trekking', 'backpack', 'camping', 'hiking', 'outdoor'],
  },
  // ---- Tablets ----
  {
    slug: 'samsung-tablet',
    title: 'Samsung Tablet',
    description: 'Samsung Galaxy Tab S8 with 11" AMOLED display, S Pen included and 128GB storage. Perfect for work and entertainment.',
    categorySlug: 'tablets',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/samsung-tablet.jpg',
    condition: 'like_new',
    city: 'Delhi',
    state: 'Delhi',
    rentalPrice: 500,
    deposit: 4000,
    rating: 4.5,
    reviewCount: 22,
    isFeatured: false,
    isTrending: false,
    features: ['11" AMOLED', 'S Pen included', '128GB storage', 'Snapdragon 8 Gen 1', 'Dolby Atmos'],
    tags: ['samsung', 'tablet', 'galaxy', 'android', 's-pen'],
  },
  {
    slug: 'ipad-pro',
    title: 'iPad Pro',
    description: 'iPad Pro 11" with M2 chip, Liquid Retina display and Apple Pencil support. 128GB storage for pro-level creativity.',
    categorySlug: 'tablets',
    ownerEmail: 'alex@example.com',
    image: '/images/products/ipad-pro.jpg',
    condition: 'like_new',
    city: 'Pune',
    state: 'Maharashtra',
    rentalPrice: 800,
    deposit: 7000,
    rating: 4.8,
    reviewCount: 36,
    isFeatured: true,
    isTrending: false,
    features: ['M2 chip', '11" Liquid Retina', 'Apple Pencil support', '128GB storage', 'Face ID'],
    tags: ['ipad', 'pro', 'apple', 'tablet', 'creative'],
    saleEnabled: true,
    salePrice: 70000,
    purchaseCondition: 'Like New — includes original box, cable and Apple Pencil',
  },
  // ---- Wearables ----
  {
    slug: 'apple-watch',
    title: 'Apple Watch',
    description: 'Apple Watch Series 9 with always-on Retina display, health tracking and GPS. 45mm aluminum case with sport band.',
    categorySlug: 'wearables',
    ownerEmail: 'priya@example.com',
    image: '/images/products/apple-watch.jpg',
    condition: 'like_new',
    city: 'Mumbai',
    state: 'Maharashtra',
    rentalPrice: 300,
    deposit: 2500,
    rating: 4.7,
    reviewCount: 41,
    isFeatured: false,
    isTrending: true,
    features: ['Always-on display', 'Health tracking', 'GPS', '45mm case', 'Sport band'],
    tags: ['apple', 'watch', 'wearable', 'fitness', 'smartwatch'],
    saleEnabled: true,
    salePrice: 28000,
    purchaseCondition: 'Like New — includes sport band and charging cable',
  },
  {
    slug: 'samsung-smartwatch',
    title: 'Samsung Smartwatch',
    description: 'Samsung Galaxy Watch 6 with AMOLED display, health monitoring and GPS. 44mm with interchangeable bands.',
    categorySlug: 'wearables',
    ownerEmail: 'rahul@example.com',
    image: '/images/products/samsung-smartwatch.jpg',
    condition: 'new',
    city: 'Bengaluru',
    state: 'Karnataka',
    rentalPrice: 250,
    deposit: 2000,
    rating: 4.4,
    reviewCount: 28,
    isFeatured: false,
    isTrending: false,
    features: ['AMOLED display', 'Health monitoring', 'GPS', '44mm case', 'Interchangeable bands'],
    tags: ['samsung', 'smartwatch', 'wearable', 'fitness', 'galaxy'],
  },
];

async function upsertUser(userData: (typeof OWNERS)[number]) {
  const salt = await bcrypt.genSalt(10);
  return User.findOneAndUpdate(
    { email: userData.email },
    {
      name: userData.name,
      email: userData.email,
      password: bcrypt.hashSync(userData.password, salt),
      role: userData.role,
      phone: userData.phone,
      avatar: '/images/demo/avatar.svg',
      verified: true,
      isEmailVerified: true,
      kycStatus: 'verified' as const,
      status: 'active' as const,
      rating: 4.9,
      location: {
        address: '',
        city: userData.city,
        state: userData.state,
        zip: '',
        coordinates: { lat: 0, lng: 0 },
      },
    },
    { upsert: true, new: true, setDefaultsOnInsert: true }
  ).exec();
}

async function seed() {
  try {
    await mongoose.connect(env.mongodbUri);
    logger.info('Connected to MongoDB for seeding');

    // ---- 1. Remove internal test/smoke products (keep real user products) ----
    const testPatternFilter = {
      $or: [
        { title: /smoke test/i },
        { title: /test camera/i },
        { title: /^test product$/i },
        { slug: /test-product/ },
      ],
    };
    const testProducts = await Product.find(testPatternFilter).select('_id').exec();
    if (testProducts.length) {
      const ids = testProducts.map((p) => p._id);
      await ProductImage.deleteMany({ product: { $in: ids } }).exec();
      const res = await Product.deleteMany({ _id: { $in: ids } }).exec();
      logger.info(`Removed ${res.deletedCount || testProducts.length} test/smoke product(s) from the demo database`);
    } else {
      logger.info('No test/smoke products found — nothing to clean');
    }

    // ---- 2. Upsert categories ----
    const categoryDocs = await Promise.all(
      CATEGORIES.map(async (cat) =>
        Category.findOneAndUpdate(
          { slug: cat.slug },
          { ...cat, status: 'active' },
          { upsert: true, new: true, setDefaultsOnInsert: true }
        ).exec()
      )
    );
    logger.info(`Upserted ${categoryDocs.length} categories`);

    // Deactivate legacy empty categories (old seed groups like "Electronics")
    // so the demo marketplace only shows categories that actually have products.
    const demoSlugs = new Set(CATEGORIES.map((c) => c.slug));
    const allCategories = await Category.find({}).select('_id slug').exec();
    const activeProductCounts = await Product.aggregate([
      { $match: { listingStatus: 'active', moderationStatus: 'approved' } },
      { $group: { _id: '$category', count: { $sum: 1 } } },
    ]).exec();
    const countByCategory = new Map(activeProductCounts.map((c) => [String(c._id), c.count as number]));
    const staleCategoryIds = allCategories
      .filter((c) => !demoSlugs.has(c.slug) && !countByCategory.has(String(c._id)))
      .map((c) => c._id);
    if (staleCategoryIds.length) {
      await Category.updateMany({ _id: { $in: staleCategoryIds } }, { $set: { status: 'inactive' } }).exec();
      logger.info(`Deactivated ${staleCategoryIds.length} legacy empty categor${staleCategoryIds.length === 1 ? 'y' : 'ies'}`);
    }

    // ---- 3. Upsert demo owners ----
    const owners = await Promise.all(OWNERS.map(upsertUser));
    const ownerByEmail = new Map(owners.map((u) => [u.email, u._id]));
    logger.info(`Upserted ${owners.length} demo owners`);

    // ---- 4. Upsert 12 unique demo products ----
    let created = 0;
    let updated = 0;
    for (const demo of PRODUCTS) {
      const category = categoryDocs.find((c) => c.slug === demo.categorySlug);
      const ownerId = ownerByEmail.get(demo.ownerEmail);
      if (!category || !ownerId) {
        logger.warn(`Skipping ${demo.title}: missing category or owner`);
        continue;
      }

      const existing = await Product.findOne({ slug: demo.slug }).select('_id').exec();
      const product = await Product.findOneAndUpdate(
        { slug: demo.slug },
        {
          slug: demo.slug,
          title: demo.title,
          description: demo.description,
          category: category._id as any,
          owner: ownerId as any,
          images: [demo.image],
          condition: demo.condition,
          location: {
            address: '',
            city: demo.city,
            state: demo.state,
            zip: '',
            coordinates: { lat: 0, lng: 0 },
          },
          rentalPrice: demo.rentalPrice,
          priceUnit: 'day',
          securityDeposit: demo.deposit,
          features: demo.features,
          tags: demo.tags,
          moderationStatus: 'approved',
          listingStatus: 'active',
          isFeatured: demo.isFeatured,
          isTrending: demo.isTrending,
          rating: demo.rating,
          reviewCount: demo.reviewCount,
          bookingsCount: Math.round(demo.reviewCount * 1.7),
          totalRevenue: 0,
          deliveryOptions: ['pickup', 'delivery', 'both'],
          cancellationPolicy: 'flexible',
          saleEnabled: demo.saleEnabled ?? false,
          salePrice: demo.salePrice ?? null,
          purchaseCondition: demo.purchaseCondition ?? null,
          productStatus: 'available',
        },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      ).exec();

      // Keep product image records in sync (defense-in-depth).
      await ProductImage.findOneAndUpdate(
        { product: product._id as any, url: demo.image },
        { product: product._id as any, url: demo.image, isPrimary: true, sortOrder: 0 },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      ).exec();

      if (existing) updated++;
      else created++;
    }
    logger.info(`Demo products ready: ${created} created, ${updated} updated`);

    const demoCount = await Product.countDocuments({ listingStatus: 'active', moderationStatus: 'approved' }).exec();
    logger.info(`✅ Seed completed successfully! ${demoCount} active approved product(s) visible`);

    await mongoose.disconnect();
    process.exit(0);
  } catch (error) {
    logger.error(`Seed failed: ${(error as Error).message}`);
    await mongoose.disconnect();
    process.exit(1);
  }
}

void seed();